<script lang="ts">
  import { onMount } from 'svelte';
  import { api,notify,showError } from '$lib/api';
  import type { Resource,RuleInput,TemplateInput,Connection,Card } from '$lib/types';
  import { kindLabels,channelLabels } from '$lib/utils';
  import Button from '$lib/components/ui/button/Button.svelte';
  import Empty from '$lib/components/Empty.svelte';
  import Loading from '$lib/components/Loading.svelte';
  let rules=$state<Resource<RuleInput>[]|null>(null),templates=$state<Resource<TemplateInput>[]>([]),connections=$state<Connection[]>([]),cards=$state<Card[]>([]);
  let edit=$state<RuleInput|null>(null),id=$state<string|null>(null),offsets=$state('7, 3, 1, 0'),busy=$state(false),error=$state('');
  async function load(){try{[rules,templates,connections,cards]=await Promise.all([api<Resource<RuleInput>[]>('/notification/rules'),api<Resource<TemplateInput>[]>('/notification/templates'),api<Connection[]>('/notification/connections'),api<Card[]>('/cards')]);}catch(e){error=e instanceof Error?e.message:'读取失败';}}
  onMount(()=>{void load();});
  function open(r?:Resource<RuleInput>){id=r?.id||null;edit=structuredClone(r?.data||{name:'还款日提醒',event_kind:'payment_due',card_ids:[],offsets:[7,3,1,0],local_time:'09:00',connection_ids:[],template_id:templates[0]?.id||'',enabled:true});offsets=edit.offsets.join(', ');}
  function toggle(field:'card_ids'|'connection_ids',value:string){if(!edit)return;const a=edit[field]||[];edit[field]=a.includes(value)?a.filter(v=>v!==value):[...a,value];}
  async function save(event:SubmitEvent){event.preventDefault();if(!edit)return;busy=true;try{const values=offsets.split(',').map(v=>Number(v.trim()));if(values.some(v=>!Number.isInteger(v))||!offsets.trim())throw new Error('提醒偏移必须是整数，使用英文逗号分隔。');await api(`/notification/rules${id?'/'+id:''}`,id?'PATCH':'POST',{...edit,offsets:values});edit=null;await load();notify('提醒规则已保存。新规则不会补发创建之前的提醒。');}catch(e){showError(e);}finally{busy=false;}}
  async function disable(r:Resource<RuleInput>){if(!confirm(`停用“${r.data.name}”及其未发送的通知？`))return;try{await api(`/notification/rules/${r.id}`,'DELETE');await load();}catch(e){showError(e);}}
</script>
<div class="stack"><div class="panel-heading"><div><h2>提醒规则</h2><small>正数表示提前，负数表示到期后；按账户时区发送。</small></div><Button onclick={()=>open()}>新建规则</Button></div>
{#if connections.length===0}<div class="hint">先<a class="underline" href="/notifications/connections">添加至少一个通知渠道</a>，再创建提醒规则。</div>{/if}
{#if edit}<form class="panel stack" onsubmit={save}><div class="panel-heading"><h2>{id?'编辑规则':'新规则'}</h2><Button variant="ghost" onclick={()=>edit=null}>关闭</Button></div><div class="form-grid"><label>规则名称<input bind:value={edit.name} required maxlength="100"/></label><label>事件类型<select bind:value={edit.event_kind}>{#each Object.entries(kindLabels) as [k,v]}<option value={k}>{v}</option>{/each}</select></label><label>偏移天数<input bind:value={offsets} required placeholder="7, 3, 1, 0, -1"/><small>7 为提前 7 天，0 为当天，-1 为到期后 1 天。</small></label><label>发送时间<input type="time" bind:value={edit.local_time} required/></label><label class="full">消息模板<select bind:value={edit.template_id} required><option value="" disabled>选择模板</option>{#each templates as t}<option value={t.id}>{t.data.name}</option>{/each}</select></label><div class="full"><h3 class="mb-3">通知渠道</h3><div class="actions">{#each connections as c}<label class="check"><input type="checkbox" checked={edit.connection_ids.includes(c.id)} onchange={()=>toggle('connection_ids',c.id)}/>{c.name} · {channelLabels[c.kind]}{c.enabled?'':'（已停用）'}</label>{/each}</div></div><div class="full"><h3 class="mb-3">信用卡范围</h3><small class="muted">不选择表示全部卡片，包括后续新增卡片。</small><div class="actions mt-3">{#each cards.filter(c=>c.active) as c}<label class="check"><input type="checkbox" checked={edit.card_ids?.includes(c.id)} onchange={()=>toggle('card_ids',c.id)}/>{c.data.name}</label>{/each}</div></div><label class="check full"><input type="checkbox" bind:checked={edit.enabled}/>启用该规则</label></div><div class="form-footer"><Button type="submit" disabled={busy}>{busy?'正在保存…':'保存规则'}</Button></div></form>{/if}
{#if error}<div class="alert error" role="alert">{error}</div>{:else if rules===null}<Loading/>{:else if !rules.length}<div class="panel"><Empty title="让提醒按时到达" description="例如还款日前 7、3、1 天及当天 09:00，通过 Bark 和邮件同时提醒。"/></div>{:else}<div class="stack">{#each rules as r}<section class="panel"><div class="panel-heading"><div class="actions"><h2>{r.data.name}</h2><span class="badge" class:success={r.data.enabled}>{r.data.enabled?'启用中':'已停用'}</span></div><div class="actions"><Button variant="outline" onclick={()=>open(r)}>编辑</Button>{#if r.data.enabled}<Button variant="ghost" onclick={()=>disable(r)}>停用</Button>{/if}</div></div><p class="text-xs">{kindLabels[r.data.event_kind]} · {r.data.local_time} · 偏移：{r.data.offsets.join(', ')} 天</p><div class="actions mt-4">{#each r.data.connection_ids as cid}<span class="badge">{connections.find(c=>c.id===cid)?.name||'未知渠道'}</span>{/each}</div><small class="muted block mt-3">模板：{templates.find(t=>t.id===r.data.template_id)?.data.name||'未知模板'} · {r.data.card_ids?.length?`${r.data.card_ids.length} 张卡`:'全部卡片'}</small></section>{/each}</div>{/if}
<div class="hint">标记已还款会取消本期未发送的还款提醒。停机后最多补发 24 小时内仍有效的提醒；已经送达服务商的消息无法撤回。</div></div>
