<script lang="ts">
  import { onMount } from 'svelte';
  import { api,notify,showError } from '$lib/api';
  import type { Resource,TemplateInput,Rendered,Connection } from '$lib/types';
  import { defaultTemplate } from '$lib/defaults';
  import Button from '$lib/components/ui/button/Button.svelte';
  import Loading from '$lib/components/Loading.svelte';
  let rows=$state<Resource<TemplateInput>[]|null>(null),connections=$state<Connection[]>([]),edit=$state<TemplateInput|null>(null),id=$state<string|null>(null),preview=$state<Rendered|null>(null),busy=$state(false),error=$state(''),testId=$state('');
  const variables=['card.name','card.issuer','card.last4','card.currency','event.type','event.label','event.date','event.days_until','cycle.statement_date','cycle.due_date','cycle.amount','cycle.minimum_payment','user.timezone','app.url'];
  async function load(){try{[rows,connections]=await Promise.all([api<Resource<TemplateInput>[]>('/notification/templates'),api<Connection[]>('/notification/connections')]);}catch(e){error=e instanceof Error?e.message:'读取失败';}}
  onMount(()=>{void load();});
  function open(row?:Resource<TemplateInput>){id=row?.id||null;edit=structuredClone(row?.data||defaultTemplate());preview=null;}
  async function validate(){if(!edit)return;busy=true;try{preview=await api<Rendered>('/notification/templates/preview','POST',edit);notify('语法与示例数据验证通过。实际发送时仍会按当期数据渲染。');}catch(e){preview=null;showError(e);}finally{busy=false;}}
  async function save(event:SubmitEvent){event.preventDefault();if(!edit)return;busy=true;try{const result=await api<{id:string}>(`/notification/templates${id?'/'+id:''}`,id?'PATCH':'POST',edit);id=result.id;await load();notify('模板已保存。未发送任务将使用更新后的模板。');}catch(e){showError(e);}finally{busy=false;}}
  async function remove(row:Resource<TemplateInput>){if(!confirm(`删除模板“${row.data.name}”？正在被规则引用的模板不能删除。`))return;try{await api(`/notification/templates/${row.id}`,'DELETE');if(id===row.id){edit=null;id=null;}await load();}catch(e){showError(e);}}
  async function sendTest(){if(!id||!testId)return;try{await api(`/notification/connections/${testId}/test`,'POST',{template_id:id});notify('已使用保存后的模板加入测试队列。');}catch(e){showError(e);}}
  function reset(){if(edit&&confirm('用默认模板内容替换当前未保存的编辑？')){const name=edit.name;edit={...defaultTemplate(),name};preview=null;}}
  function frame(html:string){return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src 'none'; form-action 'none'"><style>body{font:14px system-ui;padding:20px;line-height:1.7;color:#172239}a{color:#245ddd}</style></head><body>${html}</body></html>`;}
</script>
<div class="stack"><div class="panel-heading"><h2>消息模板</h2><Button onclick={()=>open()}>新建模板</Button></div>{#if error}<div class="alert error" role="alert">{error}</div>{:else if rows===null}<Loading/>{:else}<div class="actions">{#each rows as row}<div class="actions"><Button variant={id===row.id?'default':'outline'} onclick={()=>open(row)}>{row.data.name}</Button><button class="text-xs muted" aria-label={`删除模板 ${row.data.name}`} onclick={()=>remove(row)}>删除</button></div>{/each}</div>{/if}
{#if edit}<div class="grid-2"><form class="panel stack" onsubmit={save}><h2>模板编辑器</h2><label>模板名称<input bind:value={edit.name} required maxlength="100"/></label><label>标题 / 邮件主题<input bind:value={edit.title} maxlength="16000"/></label><label>纯文本正文<textarea class="mono" bind:value={edit.body} rows="8" maxlength="16000"></textarea></label><label>邮件 HTML（可选）<textarea class="mono" bind:value={edit.html} rows="6" maxlength="16000"></textarea></label><label>点击后的站内链接<input class="mono" bind:value={edit.url} maxlength="16000"/><small>仅允许应用自身域名下的绝对 URL，空白表示不指定。</small></label><div class="form-grid"><label>Bark 分组<input bind:value={edit.group}/></label><label>Bark 提示音<input bind:value={edit.sound}/></label><label class="full">Bark 通知等级<select bind:value={edit.level}><option value="active">Active</option><option value="passive">Passive</option><option value="timeSensitive">Time Sensitive</option></select></label></div><div class="actions"><Button type="submit" disabled={busy}>保存模板</Button><Button variant="outline" disabled={busy} onclick={validate}>验证并预览</Button><Button variant="ghost" onclick={reset}>恢复默认内容</Button></div></form>
<section class="stack"><div class="panel stack"><h2>预览</h2><small class="muted">使用不含真实账户信息的示例数据；不会自动发送。</small>{#if preview}<h3>{preview.title}</h3><pre>{preview.body}</pre>{#if preview.html}<iframe title="隔离的邮件 HTML 预览" class="preview-frame" sandbox="" referrerpolicy="no-referrer" srcdoc={frame(preview.html)}></iframe>{/if}<small class="muted break-all">{preview.url}</small>{:else}<p class="text-sm">点击“验证并预览”，查看模板渲染结果。</p>{/if}</div><div class="panel stack"><h2>可用变量</h2><div class="actions">{#each variables as variable}<code class="badge">{'{{ '+variable+' }}'}</code>{/each}</div><div class="hint">金额可能为空，请使用 {'{% if cycle.amount %}'} 判断。HTML 中的变量会转义，脚本和危险标签会被清理。模板不允许访问服务器文件、执行命令或发起网络请求。</div></div>{#if id}<div class="panel stack"><h2>发送测试消息</h2><label>目的渠道<select bind:value={testId}><option value="">选择渠道</option>{#each connections.filter(c=>c.enabled) as c}<option value={c.id}>{c.name}</option>{/each}</select></label><Button variant="outline" disabled={!testId} onclick={sendTest}>用已保存版本发送测试</Button></div>{/if}</section></div>{:else}<div class="hint">选择现有模板或创建新模板。一个模板可同时用于 Bark、邮件、Telegram、浏览器推送和 Webhook；邮件额外支持 HTML 正文。</div>{/if}</div>
