<script lang="ts">
  import { onMount } from 'svelte';
  import { CalendarDays, Copy, Plus, RefreshCw } from '@lucide/svelte';
  import { api,copy,notify,showError } from '$lib/api';
  import type { Card,Feed,FeedInput } from '$lib/types';
  import { defaultFeed } from '$lib/defaults';
  import { kindLabels } from '$lib/utils';
  import Button from '$lib/components/ui/button/Button.svelte';
  import Loading from '$lib/components/Loading.svelte';
  import Empty from '$lib/components/Empty.svelte';
  let feeds=$state<Feed[]|null>(null),cards=$state<Card[]>([]),editing=$state<FeedInput|null>(null),id=$state<string|null>(null),alarms=$state(''),busy=$state(false),error=$state('');
  async function load(){try{[feeds,cards]=await Promise.all([api<Feed[]>('/calendar/feeds'),api<Card[]>('/cards')]);}catch(e){error=e instanceof Error?e.message:'读取失败';}}
  onMount(()=>{void load();});
  function edit(f?:Feed){id=f?.id||null;editing=$state.snapshot(f?.data||defaultFeed());alarms=editing.alarms_days_before?.join(', ')||'';}
  function toggle(kind:'kinds'|'card_ids',value:string){if(!editing)return;const a=editing[kind]||[];editing[kind]=a.includes(value)?a.filter(v=>v!==value):[...a,value];}
  async function save(event:SubmitEvent){event.preventDefault();if(!editing)return;busy=true;try{const offsets=alarms.trim()?alarms.split(',').map(v=>Number(v.trim())):[];if(offsets.some(v=>!Number.isInteger(v)||v<0||v>30))throw new Error('日历提醒请填写 0–30 的整数，以英文逗号分隔。');await api(`/calendar/feeds${id?'/'+id:''}`,id?'PATCH':'POST',{...editing,alarms_days_before:[...new Set(offsets)]});editing=null;await load();notify('日历设置已保存。设备会在下一次拉取订阅时更新。');}catch(e){showError(e);}finally{busy=false;}}
  async function rotate(f:Feed){if(!confirm('重置后，旧订阅链接将立即失效。所有设备都需要添加新链接，是否继续？'))return;try{await api(`/calendar/feeds/${f.id}/rotate-token`,'POST');await load();notify('旧链接已撤销，请更新设备上的订阅。');}catch(e){showError(e);}}
  async function remove(f:Feed){if(!confirm(`删除“${f.data.name}”订阅？设备可能保留以前下载的事件，需要手动移除订阅。`))return;try{await api(`/calendar/feeds/${f.id}`,'DELETE');await load();}catch(e){showError(e);}}
</script>
<div class="page-heading"><div><div class="eyebrow">Calendar subscriptions</div><h1>你的日期，随处可见</h1><p>一个稳定的订阅地址，持续更新设备中的信用卡日程。</p></div><Button onclick={()=>edit()}><Plus size={16}/>创建订阅</Button></div>
<div class="stack"><div class="hint">请在设备日历中选择“通过 URL 订阅”，而不是下载文件后导入。ICS 更新由设备轮询决定，不是即时推送；还款提醒建议同时开启 Bark、邮件等渠道。订阅链接是私密凭证，不要公开分享。</div>
{#if editing}<form class="panel stack" onsubmit={save}><div class="panel-heading"><h2>{id?'修改订阅':'新订阅'}</h2><Button variant="ghost" onclick={()=>editing=null}>关闭</Button></div><div class="form-grid"><label>订阅名称<input bind:value={editing.name} required maxlength="100"/></label><label>隐私级别<select bind:value={editing.privacy}><option value="private">私密：只显示事项类型</option><option value="normal">普通：卡片名称和事项</option><option value="detailed">详细：再包含卡号尾四位</option></select></label><label class="check"><input type="checkbox" bind:checked={editing.enabled}/>启用订阅</label><label class="check"><input type="checkbox" bind:checked={editing.hide_paid}/>隐藏已还款事项</label><div class="full"><h3 class="mb-3">事件类型</h3><div class="actions">{#each Object.entries(kindLabels) as [kind,label]}<label class="check"><input type="checkbox" checked={editing.kinds?.includes(kind)} onchange={()=>toggle('kinds',kind)}/>{label}</label>{/each}</div></div><div class="full"><h3 class="mb-3">包含的信用卡</h3><small class="muted">不勾选表示全部信用卡。仅勾选部分卡时，不会公开其他卡片的事项。</small><div class="actions mt-3">{#each cards.filter(c=>c.active) as c}<label class="check"><input type="checkbox" checked={editing.card_ids?.includes(c.id)} onchange={()=>toggle('card_ids',c.id)}/>{c.data.name}</label>{/each}</div></div><label class="full">日历客户端提醒（可选）<input bind:value={alarms} placeholder="例如：3, 1, 0"/><small>提前天数，0 为当天。不同日历客户端可能忽略订阅源中的提醒。</small></label></div><div class="form-footer"><Button type="submit" disabled={busy}>{busy?'正在保存…':'保存订阅'}</Button></div></form>{/if}
{#if error}<div class="alert error" role="alert">{error}</div>{:else if feeds===null}<Loading/>{:else if feeds.length===0}<div class="panel"><Empty title="把信用卡日期放进设备日历" description="可按卡片或事件类型建立不同的私密订阅。"/></div>{:else}{#each feeds as f}<section class="panel stack"><div class="panel-heading"><div class="actions"><CalendarDays size={21}/><h2>{f.data.name}</h2><span class="badge" class:success={f.data.enabled}>{f.data.enabled?'已启用':'已暂停'}</span></div><Button variant="outline" onclick={()=>edit(f)}>编辑</Button></div><code class="url-box">{f.url}</code><div class="actions"><Button variant="outline" onclick={()=>copy(f.url)}><Copy size={15}/>复制订阅地址</Button><a class="button button-ghost" href={f.url.replace(/^https?:/,'webcal:')}>打开设备日历</a><Button variant="ghost" onclick={()=>rotate(f)}><RefreshCw size={14}/>重置链接</Button><Button variant="ghost" onclick={()=>remove(f)}>删除</Button></div><small class="muted">最近拉取：{f.last_accessed_at?new Date(f.last_accessed_at).toLocaleString():'尚未收到请求'}。这只说明服务器收到过请求，不代表设备已正确显示事件。</small></section>{/each}{/if}
<section class="panel"><h2 class="mb-3">如何添加订阅</h2><div class="notice-list"><p>Apple 日历：添加日历 → 添加订阅日历，粘贴 HTTPS 地址。可通过 iCloud 同步到其他设备。</p><p>Google 日历：在桌面网页“其他日历”旁选择“通过网址”，粘贴订阅地址。</p><p>Outlook：添加日历 → 从 Web 订阅。不要选择“上传文件”或一次性导入。</p><p>重置或删除链接不会擦除设备已有副本；必要时在设备中移除旧订阅后重新添加。</p></div></section></div>
