<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { api,session,refreshSession,notify,showError } from '$lib/api';
  import { setTheme } from '$lib/utils';
  import Button from '$lib/components/ui/button/Button.svelte';
  let timezone=$state(''),theme=$state('system'),current=$state(''),password=$state(''),confirmPassword=$state(''),busy=$state('');
  let system=$state<Record<string,unknown>|null>(null),audit=$state<{action:string;entity_id:string|null;created_at:string}[]>([]);
  onMount(()=>{timezone=$session?.user.timezone||'Asia/Shanghai';theme=localStorage.getItem('carddue-theme')||'system';if($session?.user.is_admin)api<Record<string,unknown>>('/settings/system').then(v=>system=v).catch(showError);api<typeof audit>('/settings/audit').then(v=>audit=v).catch(showError);});
  async function saveTimezone(event:SubmitEvent){event.preventDefault();busy='timezone';try{await api('/account','PATCH',{timezone});await refreshSession();notify('时区已更新，未发送提醒已重新安排。');}catch(e){showError(e);}finally{busy='';}}
  async function changePassword(event:SubmitEvent){event.preventDefault();if(password!==confirmPassword){notify('两次新密码不一致。',true);return;}busy='password';try{await api('/account/password','POST',{current_password:current,new_password:password});current='';password='';confirmPassword='';session.set(null);notify('密码已更改，所有会话已退出。');await goto('/login');}catch(e){showError(e);}finally{busy='';}}
  async function logout(all:boolean){if(all&&!confirm('退出所有设备上的登录会话？通知规则仍会继续运行。'))return;try{await api(all?'/auth/logout-all':'/auth/logout','POST');session.set(null);await goto('/login');}catch(e){showError(e);}}
</script>
<div class="page-heading"><div><div class="eyebrow">Preferences & security</div><h1>设置</h1><p>账户、外观、安全与系统状态。</p></div></div>
<div class="stack"><div class="grid-2"><section class="panel stack"><h2>账户与时区</h2><p class="text-sm">{$session?.user.email}</p><form class="stack" onsubmit={saveTimezone}><label>提醒时区<input bind:value={timezone} required list="timezones"/><datalist id="timezones"><option value="Asia/Shanghai"></option><option value="Asia/Hong_Kong"></option><option value="Asia/Tokyo"></option><option value="America/Los_Angeles"></option><option value="America/New_York"></option><option value="Europe/London"></option><option value="UTC"></option></datalist><small>使用 IANA 名称；不会把“UTC+8”当作固定时区存储。</small></label><Button type="submit" disabled={busy==='timezone'}>保存时区</Button></form></section><section class="panel stack"><h2>外观</h2><label>主题<select bind:value={theme} onchange={()=>setTheme(theme)}><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label><p class="text-xs">主题仅保存在当前浏览器。页面不会把账户凭据、会话 Token 或推送密钥放入 localStorage。</p><div class="hint">更换设备时，订阅日历继续使用原链接；浏览器推送需要在新设备上单独授权和绑定。</div></section></div>
<div class="grid-2"><form class="panel stack" onsubmit={changePassword}><h2>更改密码</h2><label>当前密码<input type="password" autocomplete="current-password" bind:value={current} required maxlength="256"/></label><label>新密码<input type="password" autocomplete="new-password" bind:value={password} required minlength="12" maxlength="256"/></label><label>确认新密码<input type="password" autocomplete="new-password" bind:value={confirmPassword} required minlength="12" maxlength="256"/></label><Button type="submit" disabled={busy==='password'}>更改密码并退出所有会话</Button></form><section class="panel stack"><h2>登录会话</h2><p class="text-xs">退出登录不会暂停后台通知。停止通知请停用渠道或提醒规则。</p><Button variant="outline" onclick={()=>logout(false)}>退出当前设备</Button><Button variant="outline" onclick={()=>logout(true)}>退出所有设备</Button><div class="hint">日历订阅链接独立于登录会话。怀疑链接泄露时，请在日历页面重置对应订阅。</div></section></div>
{#if system}<section class="panel stack"><h2>管理员系统状态</h2><pre>{JSON.stringify(system,null,2)}</pre><small class="muted">不显示密钥或数据库连接信息。运行角色应为 all，或另有 worker 进程负责调度。</small></section>{/if}
<section class="panel"><h2 class="mb-4">最近的账户操作</h2><div class="table-wrap"><table><thead><tr><th>时间</th><th>操作</th><th>对象 ID</th></tr></thead><tbody>{#each audit as item}<tr><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.action}</td><td class="mono text-xs">{item.entity_id||'—'}</td></tr>{/each}</tbody></table></div></section></div>
