<script lang="ts">
  import { goto } from '$app/navigation';
  import { session } from '$lib/api';
  import { regionLabel } from '$lib/card-catalog';
  import { untrack } from 'svelte';
  import { page } from '$app/state';
  import { api,notify,showError } from '$lib/api';
  import type { Card,CardInput,Cycle,CyclePatch,MilestoneInput,Resource,Dashboard } from '$lib/types';
  import { kindLabels } from '$lib/utils';
  import CardForm from '$lib/components/CardForm.svelte';
  import Loading from '$lib/components/Loading.svelte';
  import Empty from '$lib/components/Empty.svelte';
  import Button from '$lib/components/ui/button/Button.svelte';
  let card=$state<Card|null>(null),cycles=$state<Cycle[]>([]),milestones=$state<Resource<MilestoneInput>[]>([]),today=$state(''),error=$state(''),tab=$state('cycles'),scope=$state('upcoming'),busy=$state('');
  let editing=$state<Cycle|null>(null),statement=$state(''),due=$state(''),amount=$state(''),minimum=$state(''),note=$state('');
  let milestone=$state<MilestoneInput|null>(null),milestoneId=$state<string|null>(null),dateToAdd=$state(''),milestoneError=$state('');
  const recurrenceLabels:Record<string,string>={one_time:'仅一次',monthly:'每月',quarterly:'每季度（每3个月）',semiannual:'每半年（每6个月）',yearly:'每年',custom_months:'每年指定月份',custom_dates:'自定义日期'};
  function recurrenceDescription(m:MilestoneInput){if(m.recurrence==='custom_months')return '每年 '+[...(m.months??[])].sort((a,b)=>a-b).map(v=>v+'月').join('、');if(m.recurrence==='custom_dates')return '指定日期：'+[...(m.dates??[])].sort().join('、');return recurrenceLabels[m.recurrence]??m.recurrence;}
  function toggleMonth(value:number){if(!milestone)return;const values=milestone.months??[];milestone.months=values.includes(value)?values.filter(v=>v!==value):[...values,value].sort((a,b)=>a-b);}
  function addDate(){if(!milestone)return;milestoneError='';const dates=milestone.dates??[];if(!/^\d{4}-\d{2}-\d{2}$/.test(dateToAdd)||dateToAdd<milestone.start_date||dateToAdd<'2000-01-01'||dateToAdd>'2200-12-31'){milestoneError='请选择不早于开始日期的有效日期。';return;}if(dates.includes(dateToAdd)){milestoneError='该日期已添加。';return;}if(dates.length>=100){milestoneError='最多添加100个日期。';return;}milestone.dates=[...dates,dateToAdd].sort();dateToAdd='';}
  const visibleCycles=$derived(cycles.filter(c=>scope==='all'||(scope==='history'?c.cycle_month<today.slice(0,7)+'-01':c.cycle_month>=today.slice(0,7)+'-01')).sort((a,b)=>scope==='history'?b.cycle_month.localeCompare(a.cycle_month):a.cycle_month.localeCompare(b.cycle_month)));
  async function load(id:string){try{const [c,cy,m,d]=await Promise.all([api<Card>(`/cards/${id}`),api<Cycle[]>(`/cards/${id}/cycles`),api<Resource<MilestoneInput>[]>('/milestones'),api<Dashboard>('/dashboard')]);if(id!==page.params.id)return;card=c;cycles=cy;milestones=m.filter(v=>v.data.card_id===id);today=new Intl.DateTimeFormat('en-CA',{timeZone:c.data.timezone||$session?.user.timezone||d.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());error='';}catch(e){error=e instanceof Error?e.message:'加载失败';}}
  $effect(()=>{const id=page.params.id;if(id)untrack(()=>{card=null;void load(id);});});
  async function saveCard(data:CardInput){await api(`/cards/${page.params.id}`,'PATCH',data);notify('卡片规则已保存；历史已还款账期保持不变。');await load(page.params.id!);tab='cycles';}
  async function payment(c:Cycle){busy=c.id;try{await api(`/cards/${page.params.id}/cycles/${c.id}/pay`,c.paid_at?'DELETE':'POST');notify(c.paid_at?'已撤销还款标记。':'本期已标记还款。');await load(page.params.id!);}catch(e){showError(e);}finally{busy='';}}
  function editCycle(c:Cycle){editing=c;statement=c.statement_date;due=c.due_date;amount=c.amount||'';minimum=c.minimum_payment||'';note=c.note;}
  async function saveCycle(event:SubmitEvent){event.preventDefault();if(!editing)return;busy=editing.id;try{const p:CyclePatch={statement_date:statement,due_date:due,amount:amount||null,minimum_payment:minimum||null,clear_amount:!amount,clear_minimum_payment:!minimum,note};await api(`/cards/${page.params.id}/cycles/${editing.id}`,'PATCH',p);editing=null;notify('本期账单已更新。');await load(page.params.id!);}catch(e){showError(e);}finally{busy='';}}
  async function resetDates(){if(!editing||!confirm('恢复这一期按卡片规则计算的日期？金额和还款标记不变。'))return;busy=editing.id;try{await api(`/cards/${page.params.id}/cycles/${editing.id}`,'PATCH',{reset_dates:true});editing=null;await load(page.params.id!);notify('已恢复规则日期。');}catch(e){showError(e);}finally{busy='';}}
  async function toggleArchive(){if(!card||!confirm(card.active?'归档这张卡？未发送提醒将停止，但历史记录保留。':'恢复这张卡并重新生成日程？'))return;busy='archive';try{await api(`/cards/${card.id}${card.active?'':'/restore'}`,card.active?'DELETE':'POST');await load(card.id);}catch(e){showError(e);}finally{busy='';}}
  async function deleteCard(){if(!card||!confirm('永久删除“'+card.data.name+'”？该卡账期、事项、通知任务和投递记录将删除，不能撤销。已订阅日历会在刷新后取消对应事项。'))return;busy='delete';try{await api('/cards/'+card.id+'/permanent','DELETE');notify('信用卡已永久删除。');await goto('/cards');}catch(e){showError(e);}finally{busy='';}}
  function newMilestone(){milestoneId=null;milestone={card_id:page.params.id!,title:'',kind:'benefit',recurrence:'monthly',start_date:today,months:[],dates:[]};dateToAdd='';milestoneError='';}
  function editMilestone(m:Resource<MilestoneInput>){milestoneId=m.id;milestone={...$state.snapshot(m.data),months:[...(m.data.months??[])],dates:[...(m.data.dates??[])]};dateToAdd='';milestoneError='';}
  async function saveMilestone(event:SubmitEvent){event.preventDefault();if(!milestone)return;milestoneError='';if(milestone.recurrence==='custom_months'&&!(milestone.months??[]).length){milestoneError='请至少选择一个月份。';return;}if(milestone.recurrence==='custom_dates'&&(!(milestone.dates??[]).length||(milestone.dates??[]).some(d=>d<milestone!.start_date))){milestoneError='请添加至少一个日期，且所有日期不得早于开始日期。';return;}busy='milestone';try{const payload={...$state.snapshot(milestone),months:milestone.recurrence==='custom_months'?milestone.months??[]:[],dates:milestone.recurrence==='custom_dates'?milestone.dates??[]:[]};await api(`/milestones${milestoneId?'/'+milestoneId:''}`,milestoneId?'PATCH':'POST',payload);milestone=null;notify('事项已保存。');await load(page.params.id!);}catch(e){showError(e);}finally{busy='';}}
  async function removeMilestone(id:string){if(!confirm('删除此事项及其未来提醒？'))return;try{await api(`/milestones/${id}`,'DELETE');await load(page.params.id!);}catch(e){showError(e);}}
</script>
{#if error}<div class="alert error" role="alert">{error}</div>{:else if !card}<Loading/>{:else}
<div class="page-heading"><div><a class="subtle-link" href="/cards">← 全部信用卡</a><h1 class="mt-3">{card.data.name}</h1><p>{card.data.issuer} · •••• {card.data.last4||'未填写'} · {card.data.currency}</p></div><span class="badge" class:success={card.active}>{card.active?'正在管理':'已归档'}</span></div>
<p class="text-xs muted mb-4">{regionLabel(card.data.region)} · 提醒时区：{card.data.timezone||($session?.user.timezone+'（跟随账户）')}</p>
<div class="tabs" aria-label="卡片页面"><button class:active={tab==='cycles'} onclick={()=>tab='cycles'}>账期与还款</button><button class:active={tab==='milestones'} onclick={()=>tab='milestones'}>权益与自定义事项</button><button class:active={tab==='settings'} onclick={()=>tab='settings'}>卡片设置</button></div>
{#if tab==='settings'}{#key card.id+JSON.stringify(card.data)}<CardForm initial={card.data} onsave={saveCard} cancelHref={`/cards/${card.id}`}/>{/key}<div class="panel mt-6"><div class="panel-heading"><div><h2>{card.active?'归档信用卡':'恢复信用卡'}</h2><p class="text-xs mt-2">归档会停止该卡未发送的提醒，不会删除历史账期。</p></div><Button variant="outline" disabled={busy==='archive'} onclick={toggleArchive}>{card.active?'归档':'恢复'}</Button></div></div>
<div class="panel mt-6"><div class="panel-heading"><div><h2>永久删除信用卡</h2><p class="text-xs mt-2">删除该卡及账期、事项和投递记录，无法恢复；仅想暂停管理时可选择归档。</p></div><Button variant="outline" disabled={!!busy} onclick={deleteCard}>删除信用卡</Button></div></div>
{:else if tab==='cycles'}
<div class="stack">{#if editing}<section class="panel stack"><div class="panel-heading"><h2>修改 {editing.cycle_month.slice(0,7)} 账期</h2><Button variant="ghost" onclick={()=>editing=null}>关闭</Button></div><form class="stack" onsubmit={saveCycle}><div class="form-grid"><label>本期实际账单日<input type="date" bind:value={statement} required/></label><label>本期实际还款日<input type="date" bind:value={due} min={statement} required/></label><label>账单金额<input bind:value={amount} inputmode="decimal" pattern={"[0-9]{1,12}(\\.[0-9]{1,2})?"} placeholder="留空清除"/></label><label>最低还款额<input bind:value={minimum} inputmode="decimal" pattern={"[0-9]{1,12}(\\.[0-9]{1,2})?"} placeholder="留空清除"/></label><label class="full">备注<textarea bind:value={note} rows="2" maxlength="4000"></textarea></label></div><div class="actions"><Button variant="outline" disabled={!!busy} onclick={resetDates}>恢复规则日期</Button><Button type="submit" disabled={!!busy}>保存本期</Button></div></form></section>{/if}
<section class="panel"><div class="panel-heading"><h2>账期记录</h2><label><span class="sr-only">账期范围</span><select bind:value={scope}><option value="upcoming">本期与未来</option><option value="history">历史账期</option><option value="all">全部</option></select></label></div><div class="hint mb-5">默认生成本期及未来12个月，已填写的远期账期仍保留。“账期”以账单所属月份命名。标记已还款只记录你的确认，不会转账；银行临时调整日期时请修改对应账期。</div><div class="table-wrap"><table><thead><tr><th>账期</th><th>账单日</th><th>还款日</th><th>金额</th><th>状态</th><th>操作</th></tr></thead><tbody>{#each visibleCycles as c}<tr><td>{c.cycle_month.slice(0,7)}</td><td>{c.statement_date}{c.statement_overridden?' *':''}</td><td>{c.due_date}{c.due_overridden?' *':''}</td><td>{c.amount||'—'}</td><td><span class="badge" class:success={!!c.paid_at} class:danger={!c.paid_at&&c.due_date<today}>{c.paid_at?'已还款':c.due_date<today?'待核对':'待还款'}</span></td><td><div class="actions"><Button variant="outline" onclick={()=>editCycle(c)}>修改</Button><Button variant="ghost" disabled={busy===c.id} onclick={()=>payment(c)}>{c.paid_at?'撤销标记':'标记已还款'}</Button></div></td></tr>{/each}</tbody></table></div></section></div>
{:else}<div class="stack"><div class="panel-heading"><h2>权益与事项</h2><Button onclick={newMilestone}>添加事项</Button></div>{#if milestone}<form class="panel stack" onsubmit={saveMilestone}><h2>{milestoneId?'修改事项':'新事项'}</h2><div class="form-grid"><label class="full">事项名称<input bind:value={milestone.title} required maxlength="120" placeholder="例如：餐饮权益重置"/></label><label>类型<select bind:value={milestone.kind}><option value="benefit">权益重置</option><option value="annual_fee">年费</option><option value="custom">自定义</option></select></label><label>重复方式<select bind:value={milestone.recurrence}><option value="one_time">仅一次</option><option value="monthly">每月</option><option value="quarterly">每季度（每3个月）</option><option value="semiannual">每半年（每6个月）</option><option value="yearly">每年</option><option value="custom_months">每年指定月份</option><option value="custom_dates">自定义日期</option></select></label><label class="full">开始日期<input type="date" bind:value={milestone.start_date} required min="2000-01-01" max="2200-12-31"/><small>季度、半年从开始月份起算；重复事项沿用开始日期的日号，遇短月取月底。不生成开始日期以前的事项，提醒沿用卡片时区。</small></label>
{#if milestone.recurrence==='custom_months'}
<fieldset class="full month-options"><legend>每年在哪些月份重复</legend><div class="month-grid">{#each Array.from({length:12},(_,i)=>i+1) as month}<label><input type="checkbox" checked={(milestone.months??[]).includes(month)} onchange={()=>toggleMonth(month)}/>{month}月</label>{/each}</div><p class="text-xs muted mt-2">每年所选月份按开始日期的日号生成事项。</p></fieldset>
{:else if milestone.recurrence==='custom_dates'}
<div class="full stack"><label>添加独立日期<input type="date" bind:value={dateToAdd} min={milestone.start_date||'2000-01-01'} max="2200-12-31"/></label><div><Button type="button" variant="outline" onclick={addDate} disabled={(milestone.dates??[]).length>=100}>添加日期</Button></div><p class="text-xs muted">已添加 {(milestone.dates??[]).length}/100 个日期。日期各执行一次，不按年重复；可提前管理，进入未来12个月范围后自动排程。</p><ul class="custom-date-list">{#each milestone.dates??[] as date}<li><span>{date}</span><Button type="button" variant="ghost" aria-label={'删除日期 '+date} onclick={()=>{if(milestone)milestone.dates=(milestone.dates??[]).filter(d=>d!==date);}}>删除</Button></li>{/each}</ul></div>
{/if}</div>{#if milestoneError}<div class="alert error" role="alert">{milestoneError}</div>{/if}<div class="actions"><Button type="submit" disabled={busy==='milestone'}>保存事项</Button><Button variant="ghost" onclick={()=>milestone=null}>取消</Button></div></form>{/if}<section class="panel">{#each milestones as m}<div class="event-row"><div><h3>{m.data.title}</h3><p class="text-xs mt-1">{kindLabels[m.data.kind]} · {m.data.start_date} · {recurrenceDescription(m.data)}</p></div><div class="actions"><Button variant="outline" onclick={()=>editMilestone(m)}>编辑</Button><Button variant="ghost" onclick={()=>removeMilestone(m.id)}>删除</Button></div></div>{:else}<Empty title="为权益设一个日期" description="可以管理月度、季度、半年权益，或指定月份及独立日期的事项。"/>{/each}</section><div class="hint">添加事项只生成日期。需要推送时，请到通知中心创建对应类型的提醒规则。</div></div>{/if}{/if}

<style>
.month-options{border:1px solid var(--line);border-radius:8px;padding:14px;min-width:0}.month-options legend{padding:0 6px}.month-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.month-grid label{display:flex;align-items:center;gap:8px}.month-grid input{width:auto;min-height:auto}.custom-date-list{list-style:none;margin:0;padding:0;display:grid;gap:4px;max-height:280px;overflow:auto}.custom-date-list li{display:flex;align-items:center;justify-content:space-between;gap:12px}.event-row>div:first-child{min-width:0;overflow-wrap:anywhere}@media(max-width:420px){.month-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
</style>
