#!/usr/bin/env node
import { spawn } from 'node:child_process';
import { resolve } from 'node:path';
process.chdir(resolve(import.meta.dirname,'..'));
process.loadEnvFile('.env');
if(process.env.APP_ENV!=='development')throw new Error('Use a development .env generated by scripts/init-env.mjs --development.');
const database=new URL(process.env.DATABASE_URL);database.hostname='127.0.0.1';
const child=spawn('cargo',['run','--bin','carddue'],{stdio:'inherit',env:{...process.env,DATABASE_URL:database.href,APP_BASE_URL:'http://localhost:5173',APP_BIND:'127.0.0.1:8080',FRONTEND_DIR:resolve('frontend/build'),NOTIFICATION_PRIVATE_HOSTS:'127.0.0.1,localhost',ALLOW_INSECURE_NOTIFICATIONS:'true'}});
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>child.kill(signal));
child.on('error',error=>{console.error(error.message);process.exitCode=1;});
child.on('exit',code=>{process.exitCode=code??1;});
